"""empty message

Revision ID: cb8f8dafe433
Revises: None
Create Date: 2016-02-11 14:41:30.926919

"""

# revision identifiers, used by Alembic.
revision = 'cb8f8dafe433'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('admin', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'admin')
    ### end Alembic commands ###
